### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by beatelite** [CalderaWP/seo-rest-api-fields#1]
Hi, do you have any examples of how this works? I checked the wiki and it didn't have anything. 

I assume this adds yoast admin CRUD endpoints to the WP API, yes? 

If so, what are all the endpoints available?

**Comment by Shelob9** [comment]
This does not add any endpoints. It modifies the default routes for posts to show two additional fields _yoast_wpseo_title and _yoast_wpseo_description, as well as to allow you to write values to those fields. Please see the article that this plugin is example code for here: http://torquemag.io/working-with-post-meta-data-using-the-wordpress-rest-api/
